# Generated by Django 3.1.2 on 2021-09-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateField()),
                ('year', models.CharField(blank=True, max_length=5)),
                ('month', models.CharField(blank=True, max_length=5)),
                ('day', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
